name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run golangci-lint
        # You may pin to the exact commit or the version.
        # uses: golangci/golangci-lint-action@5c56cd6c9dc07901af25baab6f2b0d9f3b7c3018
        uses: golangci/golangci-lint-action@v2.5.2
        # for settings see https://github.com/golangci/golangci-lint-action
        with:
          only-new-issues: true
          # golangci-lint command line arguments
          args: --timeout=5m0s

  examples:
    name: examples
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run examples
        run: make examples
      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: allure-results
          path: ./examples/allure-results